using System;
using System.Collections.Generic;
using System.Globalization;
using System.Windows;
using System.Windows.Markup;

namespace PowerSideBar.Services;

/// <summary>
/// Simple EN/FR/ES/JA localization. Default language is English.
/// Call <see cref="SetLanguage"/> before creating UI; restart the app after a language change.
/// </summary>
public static class Loc
{
    public const string English = "en";
    public const string French = "fr";
    public const string Spanish = "es";
    public const string Japanese = "ja";

    private static string _language = English;
    private static IReadOnlyDictionary<string, string>? _strings;

    public static string Language => _language;

    public static CultureInfo Culture => _language switch
    {
        French => CultureInfo.GetCultureInfo("fr-FR"),
        Spanish => CultureInfo.GetCultureInfo("es-ES"),
        Japanese => CultureInfo.GetCultureInfo("ja-JP"),
        _ => CultureInfo.GetCultureInfo("en-US"),
    };

    public static void SetLanguage(string? language)
    {
        var lang = Normalize(language);
        _language = lang;
        _strings = lang switch
        {
            French => Fr,
            Spanish => Es,
            Japanese => Ja,
            _ => En,
        };
        try
        {
            CultureInfo.DefaultThreadCurrentCulture = Culture;
            CultureInfo.DefaultThreadCurrentUICulture = Culture;
        }
        catch
        {
            // Ignore culture failures in restricted environments.
        }
    }

    public static string Normalize(string? language)
    {
        if (string.Equals(language, French, StringComparison.OrdinalIgnoreCase))
            return French;
        if (string.Equals(language, Spanish, StringComparison.OrdinalIgnoreCase))
            return Spanish;
        if (string.Equals(language, Japanese, StringComparison.OrdinalIgnoreCase))
            return Japanese;
        return English;
    }

    public static string T(string key)
    {
        var map = _strings ?? En;
        return map.TryGetValue(key, out var value) ? value : key;
    }

    public static string Tf(string key, params object[] args) =>
        string.Format(Culture, T(key), args);

    private static readonly Dictionary<string, string> En = new()
    {
        // Common
        ["common.cancel"] = "Cancel",
        ["common.ok"] = "OK",
        ["common.add"] = "Add",
        ["common.save"] = "Save",
        ["common.loading"] = "Loading...",
        ["common.refresh"] = "Refresh",
        ["common.validation"] = "Validation",
        ["common.close"] = "Close",
        ["common.delete"] = "Delete",
        ["common.rename"] = "Rename",

        // Built-ins
        ["builtin.weather"] = "Weather",
        ["builtin.hue"] = "Hue",
        ["builtin.shutters"] = "Shutters",

        // Tray / App
        ["app.already_running"] = "PowerSideBar is already running.",
        ["tray.show_hide"] = "Show/Hide",
        ["tray.auto_start"] = "Start with Windows",
        ["tray.ad_block"] = "Ad blocker",
        ["tray.settings"] = "Settings",
        ["tray.check_updates"] = "Check for updates",
        ["tray.quit"] = "Quit",

        // Updates
        ["update.title"] = "Updates",
        ["update.dev_only"] = "Automatic updates are only available with the installed version (Setup).",
        ["update.check_failed"] = "Unable to check for updates.\n{0}",
        ["update.up_to_date"] = "You are up to date (v{0}).",
        ["update.available_title"] = "PowerSideBar update",
        ["update.available_body"] = "A new version is available: v{0}\nCurrent version: v{1}\n\nDownload and restart now?",
        ["update.apply_failed"] = "Download / install failed.\n{0}",
        ["update.version_label"] = "Installed version: v{0}",
        ["update.check_button"] = "Check for updates",

        // Settings
        ["settings.title"] = "Settings",
        ["settings.nav.general"] = "General",
        ["settings.nav.weather"] = "Weather",
        ["settings.nav.hue"] = "Philips Hue",
        ["settings.nav.shutters"] = "Shutters",
        ["settings.nav.spotify"] = "Spotify",
        ["settings.general.title"] = "General",
        ["settings.general.subtitle"] = "App behavior and sidebar appearance.",
        ["settings.auto_start"] = "Start automatically with Windows",
        ["settings.ad_block"] = "Ad blocker",
        ["settings.language"] = "Language",
        ["settings.lang.en"] = "English",
        ["settings.lang.fr"] = "French",
        ["settings.lang.es"] = "Spanish",
        ["settings.lang.ja"] = "Japanese",
        ["settings.language_restart"] = "The app will restart to apply the new language.",
        ["settings.bar_side"] = "Sidebar position",
        ["settings.side.left"] = "Left",
        ["settings.side.right"] = "Right",
        ["settings.bar_width"] = "Sidebar width",
        ["settings.width.narrow"] = "Narrow",
        ["settings.width.normal"] = "Normal",
        ["settings.width.wide"] = "Wide",
        ["settings.updates"] = "Updates",
        ["settings.support"] = "Support",
        ["settings.kofi"] = "Support me",
        ["settings.weather.title"] = "Weather",
        ["settings.weather.subtitle"] = "Search for a city or postal code via Open-Meteo, then select a result.",
        ["settings.weather.enable"] = "Show Weather in the sidebar",
        ["settings.weather.search"] = "Search for a city or postal code",
        ["settings.weather.city"] = "City: {0}",
        ["settings.weather.no_city"] = "No city selected",
        ["settings.weather.no_results"] = "No results.",
        ["settings.weather.search_error"] = "Search error. Please try again.",
        ["settings.weather.need_city"] = "Select a city from the search results before saving.",
        ["settings.weather.min_chars"] = "Enter at least 2 characters…",
        ["settings.weather.searching"] = "Searching…",
        ["settings.weather.results_count"] = "{0} result(s) — select a city.",
        ["settings.hue.title"] = "Philips Hue",
        ["settings.hue.subtitle"] = "Connect your Hue bridge and control lights from the sidebar.",
        ["settings.hue.enable"] = "Show Hue in the sidebar",
        ["settings.hue.ip"] = "Bridge IP",
        ["settings.hue.key"] = "API key",
        ["settings.shutters.title"] = "Shutters",
        ["settings.shutters.subtitle"] = "Dooya SHC box connection settings.",
        ["settings.shutters.enable"] = "Show Shutters in the sidebar",
        ["settings.shutters.host"] = "Host / IP",
        ["settings.shutters.port"] = "Port",
        ["settings.shutters.user"] = "Username",
        ["settings.shutters.password"] = "Password",
        ["settings.shutters.host_id"] = "Host ID",
        ["settings.shutters.port_invalid"] = "Invalid shutter port (1–65535).",
        ["settings.spotify.title"] = "Spotify",
        ["settings.spotify.subtitle"] = "Spotify Developer credentials for playback control.",
        ["settings.spotify.enable"] = "Show Spotify in the sidebar",
        ["settings.spotify.client_id"] = "Client ID",
        ["settings.spotify.client_secret"] = "Client Secret",

        // Sidebar chrome
        ["sidebar.back"] = "Back",
        ["sidebar.forward"] = "Forward",
        ["sidebar.home"] = "Home",
        ["sidebar.refresh"] = "Refresh",
        ["sidebar.add_shortcut"] = "Add shortcut",
        ["sidebar.settings"] = "Settings",
        ["sidebar.spotify"] = "Spotify",
        ["sidebar.like"] = "Like",
        ["sidebar.previous"] = "Previous",
        ["sidebar.play_pause"] = "Play/Pause",
        ["sidebar.next"] = "Next",
        ["menu.rename_group"] = "Rename group",
        ["menu.delete_group"] = "Delete group",
        ["menu.rename"] = "Rename",
        ["menu.user_agent"] = "User Agent",
        ["menu.ua_mobile"] = "Mobile",
        ["menu.ua_desktop"] = "Desktop",
        ["menu.keep_background"] = "Keep in background",
        ["menu.overlay"] = "Overlay mode",
        ["menu.close_on_collapse"] = "Close when collapsing",
        ["menu.close_on_collapse_tip"] = "On the second click, close the tab and free memory (otherwise it stays in the background)",
        ["menu.move_to_group"] = "Move to...",
        ["menu.close_tab"] = "Close tab",
        ["menu.delete"] = "Delete",
        ["menu.no_group"] = "No group",
        ["menu.new_group"] = "New group...",
        ["dialog.new_group"] = "New group",
        ["dialog.rename"] = "Rename",
        ["dialog.rename_group"] = "Rename group",
        ["dialog.add_shortcut"] = "Add shortcut",
        ["webview.runtime_missing"] = "WebView2 Runtime not found.\nInstall it from:\nhttps://developer.microsoft.com/en-us/microsoft-edge/webview2/\n\nError: {0}",
        ["webview.runtime_title"] = "PowerSideBar - Error",
        ["dialog.name"] = "Name:",
        ["dialog.url"] = "URL:",
        ["dialog.browse_icon"] = "Browse icon...",
        ["dialog.name_required"] = "Please enter a name.",
        ["dialog.url_required"] = "Please enter a URL.",
        ["confirm.delete_shortcut"] = "Delete shortcut \"{0}\"?",
        ["confirm.delete_group"] = "Delete group \"{0}\"? Shortcuts will be ungrouped.",
        ["confirm.title"] = "Confirm",

        // Weather panel
        ["weather.loading"] = "Loading...",
        ["weather.gusts"] = "Gusts",
        ["weather.next_days"] = "NEXT DAYS",
        ["weather.today"] = "TODAY",
        ["weather.load_error"] = "Unable to load weather.\nCheck your connection.",
        ["weather.clear"] = "Clear sky",
        ["weather.mainly_clear"] = "Mainly clear",
        ["weather.partly_cloudy"] = "Partly cloudy",
        ["weather.overcast"] = "Overcast",
        ["weather.fog"] = "Fog",
        ["weather.drizzle_light"] = "Light drizzle",
        ["weather.drizzle"] = "Drizzle",
        ["weather.drizzle_dense"] = "Dense drizzle",
        ["weather.drizzle_freezing"] = "Freezing drizzle",
        ["weather.rain_light"] = "Light rain",
        ["weather.rain"] = "Rain",
        ["weather.rain_heavy"] = "Heavy rain",
        ["weather.rain_freezing"] = "Freezing rain",
        ["weather.snow_light"] = "Light snow",
        ["weather.snow"] = "Snow",
        ["weather.snow_heavy"] = "Heavy snow",
        ["weather.snow_grains"] = "Snow grains",
        ["weather.showers_light"] = "Light showers",
        ["weather.showers"] = "Showers",
        ["weather.showers_violent"] = "Violent showers",
        ["weather.snow_showers"] = "Snow showers",
        ["weather.snow_showers_heavy"] = "Heavy snow showers",
        ["weather.thunderstorm"] = "Thunderstorm",
        ["weather.thunderstorm_hail"] = "Thunderstorm / hail",
        ["weather.unknown"] = "Unknown",

        // Hue
        ["hue.connect_network"] = "Connect your Philips Hue bridge to the same network as this PC.",
        ["hue.search_bridge"] = "Search for bridge",
        ["hue.searching"] = "Searching for bridge...",
        ["hue.bridge_found"] = "Bridge found",
        ["hue.press_button_1"] = "Press the ",
        ["hue.press_button_2"] = "physical button",
        ["hue.press_button_3"] = " on the bridge,\nthen click Connect.",
        ["hue.connect"] = "Connect",
        ["hue.connecting"] = "Connecting...",
        ["hue.retry"] = "Retry",
        ["hue.reconfigure"] = "Reconfigure bridge",
        ["hue.home"] = "Home",
        ["hue.rooms"] = "ROOMS",
        ["hue.scenes"] = "SCENES",
        ["hue.lights"] = "LIGHTS",
        ["hue.no_rooms"] = "No rooms found.\nCheck your Hue configuration.",
        ["hue.bridge_error"] = "Bridge connection error:\n{0}",
        ["hue.no_bridge"] = "No Philips Hue bridge found on the network.\nMake sure it is powered on and connected.",
        ["hue.pair_error"] = "Pairing error.",

        // Shutters
        ["shutters.connecting"] = "Connecting to the box…",
        ["shutters.reconnect"] = "Reconnect",
        ["shutters.title"] = "Shutters",
        ["shutters.all"] = "ALL SHUTTERS",
        ["shutters.up"] = "Up",
        ["shutters.stop"] = "Stop",
        ["shutters.down"] = "Down",
        ["shutters.all_up"] = "Raise all",
        ["shutters.all_stop"] = "Stop all",
        ["shutters.all_down"] = "Lower all",
        ["shutters.ground_floor"] = "GROUND FLOOR",
        ["shutters.floor"] = "UPPER FLOOR",
        ["shutters.close_floor"] = "Close",
        ["shutters.close_gf_tip"] = "Close ground floor",
        ["shutters.close_floor_tip"] = "Close upper floor",
        ["shutters.sending"] = "Sending…",
        ["shutters.connect_failed"] = "Unable to connect to {0}:{1}.\nCheck the IP and credentials in Settings.",
        ["shutters.auth_failed"] = "Authentication failed (user: {0}).\n{1}",
        ["shutters.timeout"] = "Timed out connecting to {0}:{1}.\nIs the box powered on and reachable?",
        ["shutters.network_error"] = "Network error: {0}\n({1}:{2})",
        ["shutters.connect_error"] = "Connection error: {0}",
        ["shutters.login_no_response"] = "No response after login (~{0} ms).",
        ["shutters.login_response"] = "Response: \"{0}\" ({1})\nRead duration: {2} ms",
        ["shutters.conn_closed"] = "Connection closed.",
        ["shutters.hver_no_response"] = "HverRsp: no response or frame too short.",
        ["shutters.hver_unexpected"] = "After HverReq, received: {0} (expected HverRsp).",
        ["shutters.dall_empty"] = "DallRsp received: deviceCount={0}. No device filtered as a shutter.",
        ["shutters.frames_no_dall"] = "Frames received: {0}. No DallRsp.",
        ["shutters.no_frames"] = "No frames received after GetaReq (15s timeout).",
        ["shutters.timeout_frames"] = "Timeout. Frames: {0}. No DallRsp.",
        ["shutters.timeout_geta"] = "15s timeout after GetaReq.",
        ["shutters.error"] = "Error: {0}",
        ["shutters.none_found"] = "Connected, but no shutters found on the box.",
        ["shutters.none_found_diag"] = "Connected, but no shutters found on the box.\n\nDiagnostic: {0}",

        // Spotify
        ["spotify.not_connected"] = "Not connected",
        ["spotify.connect"] = "Connect to Spotify",
        ["spotify.no_playback"] = "Nothing playing",
        ["spotify.disconnect"] = "Disconnect",
        ["spotify.on_device"] = "On: {0}",
        ["spotify.connected"] = "Connected",
        ["spotify.connected_ok"] = "Connected to Spotify",
        ["spotify.not_configured"] = "Spotify Client ID / Secret not configured",
        ["spotify.disconnected"] = "Disconnected",
        ["spotify.opening_browser"] = "Opening browser...",
        ["spotify.browser_failed"] = "Unable to open the browser",
        ["spotify.wait_auth"] = "Waiting for authorization in the browser...",
        ["spotify.auth_cancelled"] = "Authorization cancelled",
        ["spotify.exchanging"] = "Exchanging code...",
        ["spotify.auth_failed"] = "Authentication failed",
        ["spotify.auth_error"] = "Authorization error",
        ["spotify.session_expired"] = "Session expired",
        ["spotify.session_expired_reauth"] = "Session expired, please reconnect",
        ["spotify.premium_required"] = "Spotify Premium required",
        ["spotify.premium_playback"] = "Spotify Premium required to control playback",
        ["spotify.no_device_volume"] = "No active Spotify device to set volume",
        ["spotify.playing"] = "Playing",
        ["spotify.paused"] = "Paused",
        ["spotify.no_playback_status"] = "Nothing playing",
        ["spotify.fetch_error"] = "Error while fetching playback",
        ["spotify.searching_device"] = "Looking for a Spotify device...",
        ["spotify.no_device"] = "No Spotify device available. Open Spotify on a device, then try again.",
        ["spotify.transferring"] = "Transferring to {0}...",
        ["spotify.transfer_failed"] = "Unable to transfer playback",
        ["spotify.api_error"] = "Spotify API error",
        ["spotify.no_track_like"] = "No Spotify track to add to Liked Songs",
        ["spotify.like_auth"] = "Spotify authorization required for Liked Songs",
        ["spotify.like_scope"] = "Spotify did not grant Liked Songs permissions",
        ["spotify.like_unsupported"] = "This content cannot be added to Liked Songs",
        ["spotify.like_failed"] = "Liked Songs failed: {0}",
        ["spotify.like_error"] = "Error updating Liked Songs",
        ["spotify.oauth_fail_title"] = "Connection failed",
        ["spotify.oauth_ok_title"] = "Connected",
        ["spotify.oauth_ok_body"] = "You can close this window and return to PowerSideBar.",
        ["spotify.unknown_error"] = "Unknown error",
    };

    private static readonly Dictionary<string, string> Fr = new()
    {
        ["common.cancel"] = "Annuler",
        ["common.ok"] = "OK",
        ["common.add"] = "Ajouter",
        ["common.save"] = "Enregistrer",
        ["common.loading"] = "Chargement...",
        ["common.refresh"] = "Actualiser",
        ["common.validation"] = "Validation",
        ["common.close"] = "Fermer",
        ["common.delete"] = "Supprimer",
        ["common.rename"] = "Renommer",

        ["builtin.weather"] = "Météo",
        ["builtin.hue"] = "Hue",
        ["builtin.shutters"] = "Volets",

        ["app.already_running"] = "PowerSideBar est déjà en cours d'exécution.",
        ["tray.show_hide"] = "Afficher/Masquer",
        ["tray.auto_start"] = "Démarrage auto",
        ["tray.ad_block"] = "Bloqueur de pub",
        ["tray.settings"] = "Paramètres",
        ["tray.check_updates"] = "Vérifier les mises à jour",
        ["tray.quit"] = "Quitter",

        ["update.title"] = "Mises à jour",
        ["update.dev_only"] = "Les mises à jour automatiques sont disponibles uniquement avec la version installée (Setup).",
        ["update.check_failed"] = "Impossible de vérifier les mises à jour.\n{0}",
        ["update.up_to_date"] = "Vous êtes à jour (v{0}).",
        ["update.available_title"] = "Mise à jour PowerSideBar",
        ["update.available_body"] = "Une nouvelle version est disponible : v{0}\nVersion actuelle : v{1}\n\nTélécharger et redémarrer maintenant ?",
        ["update.apply_failed"] = "Échec du téléchargement / de l'installation.\n{0}",
        ["update.version_label"] = "Version installée : v{0}",
        ["update.check_button"] = "Vérifier les mises à jour",

        ["settings.title"] = "Paramètres",
        ["settings.nav.general"] = "Général",
        ["settings.nav.weather"] = "Météo",
        ["settings.nav.hue"] = "Philips Hue",
        ["settings.nav.shutters"] = "Volets",
        ["settings.nav.spotify"] = "Spotify",
        ["settings.general.title"] = "Général",
        ["settings.general.subtitle"] = "Comportement de l'application et apparence de la barre.",
        ["settings.auto_start"] = "Démarrage automatique avec Windows",
        ["settings.ad_block"] = "Bloqueur de publicités",
        ["settings.language"] = "Langue",
        ["settings.lang.en"] = "Anglais",
        ["settings.lang.fr"] = "Français",
        ["settings.lang.es"] = "Espagnol",
        ["settings.lang.ja"] = "Japonais",
        ["settings.language_restart"] = "L'application va redémarrer pour appliquer la nouvelle langue.",
        ["settings.bar_side"] = "Position de la barre",
        ["settings.side.left"] = "Gauche",
        ["settings.side.right"] = "Droite",
        ["settings.bar_width"] = "Largeur de la barre",
        ["settings.width.narrow"] = "Étroit",
        ["settings.width.normal"] = "Normal",
        ["settings.width.wide"] = "Large",
        ["settings.updates"] = "Mises à jour",
        ["settings.support"] = "Soutien",
        ["settings.kofi"] = "Soutenez-moi",
        ["settings.weather.title"] = "Météo",
        ["settings.weather.subtitle"] = "Recherchez une ville ou un code postal via Open-Meteo, puis sélectionnez un résultat.",
        ["settings.weather.enable"] = "Afficher Météo dans la barre",
        ["settings.weather.search"] = "Rechercher une ville ou un code postal",
        ["settings.weather.city"] = "Ville : {0}",
        ["settings.weather.no_city"] = "Aucune ville sélectionnée",
        ["settings.weather.no_results"] = "Aucun résultat.",
        ["settings.weather.search_error"] = "Erreur de recherche. Réessayez.",
        ["settings.weather.need_city"] = "Sélectionnez une ville dans les résultats avant d'enregistrer.",
        ["settings.weather.min_chars"] = "Saisissez au moins 2 caractères…",
        ["settings.weather.searching"] = "Recherche…",
        ["settings.weather.results_count"] = "{0} résultat(s) — sélectionnez une ville.",
        ["settings.hue.title"] = "Philips Hue",
        ["settings.hue.subtitle"] = "Connectez votre bridge Hue et contrôlez les lumières depuis la barre.",
        ["settings.hue.enable"] = "Afficher Hue dans la barre",
        ["settings.hue.ip"] = "IP du bridge",
        ["settings.hue.key"] = "Clé API",
        ["settings.shutters.title"] = "Volets",
        ["settings.shutters.subtitle"] = "Paramètres de connexion au boîtier Dooya SHC.",
        ["settings.shutters.enable"] = "Afficher Volets dans la barre",
        ["settings.shutters.host"] = "Hôte / IP",
        ["settings.shutters.port"] = "Port",
        ["settings.shutters.user"] = "Utilisateur",
        ["settings.shutters.password"] = "Mot de passe",
        ["settings.shutters.host_id"] = "Host ID",
        ["settings.shutters.port_invalid"] = "Port volets invalide (1–65535).",
        ["settings.spotify.title"] = "Spotify",
        ["settings.spotify.subtitle"] = "Identifiants Spotify Developer pour le contrôle de la lecture.",
        ["settings.spotify.enable"] = "Afficher Spotify dans la barre",
        ["settings.spotify.client_id"] = "Client ID",
        ["settings.spotify.client_secret"] = "Client Secret",

        ["sidebar.back"] = "Retour",
        ["sidebar.forward"] = "Avancer",
        ["sidebar.home"] = "Accueil",
        ["sidebar.refresh"] = "Rafraîchir",
        ["sidebar.add_shortcut"] = "Ajouter un raccourci",
        ["sidebar.settings"] = "Paramètres",
        ["sidebar.spotify"] = "Spotify",
        ["sidebar.like"] = "J'aime",
        ["sidebar.previous"] = "Précédent",
        ["sidebar.play_pause"] = "Play/Pause",
        ["sidebar.next"] = "Suivant",
        ["menu.rename_group"] = "Renommer le groupe",
        ["menu.delete_group"] = "Supprimer le groupe",
        ["menu.rename"] = "Renommer",
        ["menu.user_agent"] = "User Agent",
        ["menu.ua_mobile"] = "Mobile",
        ["menu.ua_desktop"] = "Desktop",
        ["menu.keep_background"] = "Garder en arrière-plan",
        ["menu.overlay"] = "Passer par-dessus",
        ["menu.close_on_collapse"] = "Fermer en réduisant",
        ["menu.close_on_collapse_tip"] = "Au second clic, ferme l'onglet et libère la mémoire (sinon il reste en arrière-plan)",
        ["menu.move_to_group"] = "Déplacer vers...",
        ["menu.close_tab"] = "Fermer l'onglet",
        ["menu.delete"] = "Supprimer",
        ["menu.no_group"] = "Aucun groupe",
        ["menu.new_group"] = "Nouveau groupe...",
        ["dialog.new_group"] = "Nouveau groupe",
        ["dialog.rename"] = "Renommer",
        ["dialog.rename_group"] = "Renommer le groupe",
        ["dialog.add_shortcut"] = "Ajouter un raccourci",
        ["webview.runtime_missing"] = "WebView2 Runtime introuvable.\nInstallez-le depuis :\nhttps://developer.microsoft.com/en-us/microsoft-edge/webview2/\n\nErreur : {0}",
        ["webview.runtime_title"] = "PowerSideBar - Erreur",
        ["dialog.name"] = "Nom :",
        ["dialog.url"] = "URL :",
        ["dialog.browse_icon"] = "Parcourir icône...",
        ["dialog.name_required"] = "Veuillez entrer un nom.",
        ["dialog.url_required"] = "Veuillez entrer une URL.",
        ["confirm.delete_shortcut"] = "Supprimer le raccourci « {0} » ?",
        ["confirm.delete_group"] = "Supprimer le groupe « {0} » ? Les raccourcis seront détachés.",
        ["confirm.title"] = "Confirmation",

        ["weather.loading"] = "Chargement...",
        ["weather.gusts"] = "Raf.",
        ["weather.next_days"] = "PROCHAINS JOURS",
        ["weather.today"] = "AUJOURD'HUI",
        ["weather.load_error"] = "Impossible de charger la météo.\nVérifiez votre connexion.",
        ["weather.clear"] = "Ciel clair",
        ["weather.mainly_clear"] = "Mitigé",
        ["weather.partly_cloudy"] = "Peu nuageux",
        ["weather.overcast"] = "Couvert",
        ["weather.fog"] = "Brouillard",
        ["weather.drizzle_light"] = "Bruine légère",
        ["weather.drizzle"] = "Bruine",
        ["weather.drizzle_dense"] = "Bruine dense",
        ["weather.drizzle_freezing"] = "Bruine verglaçante",
        ["weather.rain_light"] = "Pluie légère",
        ["weather.rain"] = "Pluie",
        ["weather.rain_heavy"] = "Pluie forte",
        ["weather.rain_freezing"] = "Pluie verglaçante",
        ["weather.snow_light"] = "Neige légère",
        ["weather.snow"] = "Neige",
        ["weather.snow_heavy"] = "Neige forte",
        ["weather.snow_grains"] = "Grains de neige",
        ["weather.showers_light"] = "Averses légères",
        ["weather.showers"] = "Averses",
        ["weather.showers_violent"] = "Averses violentes",
        ["weather.snow_showers"] = "Averses de neige",
        ["weather.snow_showers_heavy"] = "Fortes averses de neige",
        ["weather.thunderstorm"] = "Orage",
        ["weather.thunderstorm_hail"] = "Orage / grêle",
        ["weather.unknown"] = "Inconnu",

        ["hue.connect_network"] = "Connectez votre bridge Philips Hue au même réseau que ce PC.",
        ["hue.search_bridge"] = "Rechercher le bridge",
        ["hue.searching"] = "Recherche du bridge en cours...",
        ["hue.bridge_found"] = "Bridge trouvé",
        ["hue.press_button_1"] = "Appuyez sur le ",
        ["hue.press_button_2"] = "bouton physique",
        ["hue.press_button_3"] = " du bridge,\npuis cliquez sur Connecter.",
        ["hue.connect"] = "Connecter",
        ["hue.connecting"] = "Connexion en cours...",
        ["hue.retry"] = "Réessayer",
        ["hue.reconfigure"] = "Reconfigurer le bridge",
        ["hue.home"] = "Maison",
        ["hue.rooms"] = "PIÈCES",
        ["hue.scenes"] = "SCÈNES",
        ["hue.lights"] = "LUMIÈRES",
        ["hue.no_rooms"] = "Aucune pièce trouvée.\nVérifiez la configuration Hue.",
        ["hue.bridge_error"] = "Erreur de connexion au bridge :\n{0}",
        ["hue.no_bridge"] = "Aucun bridge Philips Hue trouvé sur le réseau.\nVérifiez qu'il est allumé et connecté.",
        ["hue.pair_error"] = "Erreur de couplage.",

        ["shutters.connecting"] = "Connexion au boîtier…",
        ["shutters.reconnect"] = "Reconnecter",
        ["shutters.title"] = "Volets",
        ["shutters.all"] = "TOUS LES VOLETS",
        ["shutters.up"] = "Monter",
        ["shutters.stop"] = "Stop",
        ["shutters.down"] = "Descendre",
        ["shutters.all_up"] = "Tout monter",
        ["shutters.all_stop"] = "Tout arrêter",
        ["shutters.all_down"] = "Tout descendre",
        ["shutters.ground_floor"] = "REZ-DE-CHAUSSÉE",
        ["shutters.floor"] = "ÉTAGE",
        ["shutters.close_floor"] = "Fermer",
        ["shutters.close_gf_tip"] = "Fermer le RDC",
        ["shutters.close_floor_tip"] = "Fermer l'étage",
        ["shutters.sending"] = "Envoi…",
        ["shutters.connect_failed"] = "Impossible de se connecter à {0}:{1}.\nVérifiez l'IP et les identifiants dans les paramètres.",
        ["shutters.auth_failed"] = "Échec auth (user: {0}).\n{1}",
        ["shutters.timeout"] = "Délai d'attente dépassé pour {0}:{1}.\nLe boîtier est-il allumé et accessible ?",
        ["shutters.network_error"] = "Erreur réseau : {0}\n({1}:{2})",
        ["shutters.connect_error"] = "Erreur de connexion : {0}",
        ["shutters.login_no_response"] = "Aucune réponse après login (~{0} ms).",
        ["shutters.login_response"] = "Réponse: \"{0}\" ({1})\nDurée lecture: {2} ms",
        ["shutters.conn_closed"] = "Connexion fermée.",
        ["shutters.hver_no_response"] = "HverRsp: aucune réponse ou trame trop courte.",
        ["shutters.hver_unexpected"] = "Après HverReq, reçu: {0} (attendu HverRsp).",
        ["shutters.dall_empty"] = "DallRsp reçu: deviceCount={0}. Aucun device filtré comme volet.",
        ["shutters.frames_no_dall"] = "Trames reçues: {0}. Pas de DallRsp.",
        ["shutters.no_frames"] = "Aucune trame reçue après GetaReq (timeout 15s).",
        ["shutters.timeout_frames"] = "Timeout. Trames: {0}. Pas de DallRsp.",
        ["shutters.timeout_geta"] = "Timeout 15s après GetaReq.",
        ["shutters.error"] = "Erreur: {0}",
        ["shutters.none_found"] = "Connecté, mais aucun volet trouvé sur le boîtier.",
        ["shutters.none_found_diag"] = "Connecté, mais aucun volet trouvé sur le boîtier.\n\nDiagnostic: {0}",

        ["spotify.not_connected"] = "Non connecté",
        ["spotify.connect"] = "Se connecter à Spotify",
        ["spotify.no_playback"] = "Aucune lecture",
        ["spotify.disconnect"] = "Se déconnecter",
        ["spotify.on_device"] = "Sur : {0}",
        ["spotify.connected"] = "Connecté",
        ["spotify.connected_ok"] = "Connecté à Spotify",
        ["spotify.not_configured"] = "Client ID / Secret Spotify non configurés",
        ["spotify.disconnected"] = "Déconnecté",
        ["spotify.opening_browser"] = "Ouverture du navigateur...",
        ["spotify.browser_failed"] = "Impossible d'ouvrir le navigateur",
        ["spotify.wait_auth"] = "En attente de l'autorisation dans le navigateur...",
        ["spotify.auth_cancelled"] = "Autorisation annulée",
        ["spotify.exchanging"] = "Échange du code...",
        ["spotify.auth_failed"] = "Échec de l'authentification",
        ["spotify.auth_error"] = "Erreur lors de l'autorisation",
        ["spotify.session_expired"] = "Session expirée",
        ["spotify.session_expired_reauth"] = "Session expirée, reconnectez-vous",
        ["spotify.premium_required"] = "Spotify Premium requis",
        ["spotify.premium_playback"] = "Spotify Premium requis pour contrôler la lecture",
        ["spotify.no_device_volume"] = "Aucun appareil Spotify actif pour régler le volume",
        ["spotify.playing"] = "En lecture",
        ["spotify.paused"] = "En pause",
        ["spotify.no_playback_status"] = "Aucune lecture en cours",
        ["spotify.fetch_error"] = "Erreur lors de la récupération",
        ["spotify.searching_device"] = "Recherche d'un appareil Spotify...",
        ["spotify.no_device"] = "Aucun appareil Spotify disponible. Ouvrez Spotify sur un appareil puis réessayez.",
        ["spotify.transferring"] = "Transfert vers {0}...",
        ["spotify.transfer_failed"] = "Impossible de transférer la lecture",
        ["spotify.api_error"] = "Erreur de l'API Spotify",
        ["spotify.no_track_like"] = "Aucun morceau Spotify à ajouter en favoris",
        ["spotify.like_auth"] = "Autorisation Spotify requise pour les favoris",
        ["spotify.like_scope"] = "Spotify n'a pas accordé les permissions Favoris",
        ["spotify.like_unsupported"] = "Ce contenu ne peut pas être ajouté aux favoris",
        ["spotify.like_failed"] = "Favoris KO: {0}",
        ["spotify.like_error"] = "Erreur lors de la mise à jour des favoris",
        ["spotify.oauth_fail_title"] = "Échec de la connexion",
        ["spotify.oauth_ok_title"] = "Connexion réussie",
        ["spotify.oauth_ok_body"] = "Vous pouvez fermer cette fenêtre et revenir à PowerSideBar.",
        ["spotify.unknown_error"] = "Erreur inconnue",
    };

    private static readonly Dictionary<string, string> Es = new()
    {
        ["common.cancel"] = "Cancelar",
        ["common.ok"] = "OK",
        ["common.add"] = "Añadir",
        ["common.save"] = "Guardar",
        ["common.loading"] = "Cargando...",
        ["common.refresh"] = "Actualizar",
        ["common.validation"] = "Validación",
        ["common.close"] = "Cerrar",
        ["common.delete"] = "Eliminar",
        ["common.rename"] = "Renombrar",

        ["builtin.weather"] = "Tiempo",
        ["builtin.hue"] = "Hue",
        ["builtin.shutters"] = "Persianas",

        ["app.already_running"] = "PowerSideBar ya se está ejecutando.",
        ["tray.show_hide"] = "Mostrar/Ocultar",
        ["tray.auto_start"] = "Inicio con Windows",
        ["tray.ad_block"] = "Bloqueador de anuncios",
        ["tray.settings"] = "Ajustes",
        ["tray.check_updates"] = "Buscar actualizaciones",
        ["tray.quit"] = "Salir",

        ["update.title"] = "Actualizaciones",
        ["update.dev_only"] = "Las actualizaciones automáticas solo están disponibles con la versión instalada (Setup).",
        ["update.check_failed"] = "No se pudieron comprobar las actualizaciones.\n{0}",
        ["update.up_to_date"] = "Estás al día (v{0}).",
        ["update.available_title"] = "Actualización de PowerSideBar",
        ["update.available_body"] = "Hay una nueva versión disponible: v{0}\nVersión actual: v{1}\n\n¿Descargar y reiniciar ahora?",
        ["update.apply_failed"] = "Error al descargar / instalar.\n{0}",
        ["update.version_label"] = "Versión instalada: v{0}",
        ["update.check_button"] = "Buscar actualizaciones",

        ["settings.title"] = "Ajustes",
        ["settings.nav.general"] = "General",
        ["settings.nav.weather"] = "Tiempo",
        ["settings.nav.hue"] = "Philips Hue",
        ["settings.nav.shutters"] = "Persianas",
        ["settings.nav.spotify"] = "Spotify",
        ["settings.general.title"] = "General",
        ["settings.general.subtitle"] = "Comportamiento de la aplicación y aspecto de la barra.",
        ["settings.auto_start"] = "Iniciar automáticamente con Windows",
        ["settings.ad_block"] = "Bloqueador de anuncios",
        ["settings.language"] = "Idioma",
        ["settings.lang.en"] = "Inglés",
        ["settings.lang.fr"] = "Francés",
        ["settings.lang.es"] = "Español",
        ["settings.lang.ja"] = "Japonés",
        ["settings.language_restart"] = "La aplicación se reiniciará para aplicar el nuevo idioma.",
        ["settings.bar_side"] = "Posición de la barra",
        ["settings.side.left"] = "Izquierda",
        ["settings.side.right"] = "Derecha",
        ["settings.bar_width"] = "Ancho de la barra",
        ["settings.width.narrow"] = "Estrecho",
        ["settings.width.normal"] = "Normal",
        ["settings.width.wide"] = "Ancho",
        ["settings.updates"] = "Actualizaciones",
        ["settings.support"] = "Apoyo",
        ["settings.kofi"] = "Apóyame",
        ["settings.weather.title"] = "Tiempo",
        ["settings.weather.subtitle"] = "Busca una ciudad o código postal con Open-Meteo y selecciona un resultado.",
        ["settings.weather.enable"] = "Mostrar Tiempo en la barra",
        ["settings.weather.search"] = "Buscar una ciudad o código postal",
        ["settings.weather.city"] = "Ciudad: {0}",
        ["settings.weather.no_city"] = "Ninguna ciudad seleccionada",
        ["settings.weather.no_results"] = "Sin resultados.",
        ["settings.weather.search_error"] = "Error de búsqueda. Inténtalo de nuevo.",
        ["settings.weather.need_city"] = "Selecciona una ciudad de los resultados antes de guardar.",
        ["settings.weather.min_chars"] = "Introduce al menos 2 caracteres…",
        ["settings.weather.searching"] = "Buscando…",
        ["settings.weather.results_count"] = "{0} resultado(s) — selecciona una ciudad.",
        ["settings.hue.title"] = "Philips Hue",
        ["settings.hue.subtitle"] = "Conecta tu puente Hue y controla las luces desde la barra.",
        ["settings.hue.enable"] = "Mostrar Hue en la barra",
        ["settings.hue.ip"] = "IP del puente",
        ["settings.hue.key"] = "Clave API",
        ["settings.shutters.title"] = "Persianas",
        ["settings.shutters.subtitle"] = "Ajustes de conexión a la caja Dooya SHC.",
        ["settings.shutters.enable"] = "Mostrar Persianas en la barra",
        ["settings.shutters.host"] = "Host / IP",
        ["settings.shutters.port"] = "Puerto",
        ["settings.shutters.user"] = "Usuario",
        ["settings.shutters.password"] = "Contraseña",
        ["settings.shutters.host_id"] = "Host ID",
        ["settings.shutters.port_invalid"] = "Puerto de persianas no válido (1–65535).",
        ["settings.spotify.title"] = "Spotify",
        ["settings.spotify.subtitle"] = "Credenciales de Spotify Developer para controlar la reproducción.",
        ["settings.spotify.enable"] = "Mostrar Spotify en la barra",
        ["settings.spotify.client_id"] = "Client ID",
        ["settings.spotify.client_secret"] = "Client Secret",

        ["sidebar.back"] = "Atrás",
        ["sidebar.forward"] = "Adelante",
        ["sidebar.home"] = "Inicio",
        ["sidebar.refresh"] = "Actualizar",
        ["sidebar.add_shortcut"] = "Añadir acceso directo",
        ["sidebar.settings"] = "Ajustes",
        ["sidebar.spotify"] = "Spotify",
        ["sidebar.like"] = "Me gusta",
        ["sidebar.previous"] = "Anterior",
        ["sidebar.play_pause"] = "Play/Pause",
        ["sidebar.next"] = "Siguiente",
        ["menu.rename_group"] = "Renombrar grupo",
        ["menu.delete_group"] = "Eliminar grupo",
        ["menu.rename"] = "Renombrar",
        ["menu.user_agent"] = "User Agent",
        ["menu.ua_mobile"] = "Móvil",
        ["menu.ua_desktop"] = "Escritorio",
        ["menu.keep_background"] = "Mantener en segundo plano",
        ["menu.overlay"] = "Modo superposición",
        ["menu.close_on_collapse"] = "Cerrar al contraer",
        ["menu.close_on_collapse_tip"] = "En el segundo clic, cierra la pestaña y libera memoria (si no, permanece en segundo plano)",
        ["menu.move_to_group"] = "Mover a...",
        ["menu.close_tab"] = "Cerrar pestaña",
        ["menu.delete"] = "Eliminar",
        ["menu.no_group"] = "Sin grupo",
        ["menu.new_group"] = "Nuevo grupo...",
        ["dialog.new_group"] = "Nuevo grupo",
        ["dialog.rename"] = "Renombrar",
        ["dialog.rename_group"] = "Renombrar grupo",
        ["dialog.add_shortcut"] = "Añadir acceso directo",
        ["webview.runtime_missing"] = "No se encontró WebView2 Runtime.\nInstálalo desde:\nhttps://developer.microsoft.com/en-us/microsoft-edge/webview2/\n\nError: {0}",
        ["webview.runtime_title"] = "PowerSideBar - Error",
        ["dialog.name"] = "Nombre:",
        ["dialog.url"] = "URL:",
        ["dialog.browse_icon"] = "Elegir icono...",
        ["dialog.name_required"] = "Introduce un nombre.",
        ["dialog.url_required"] = "Introduce una URL.",
        ["confirm.delete_shortcut"] = "¿Eliminar el acceso directo \"{0}\"?",
        ["confirm.delete_group"] = "¿Eliminar el grupo \"{0}\"? Los accesos directos quedarán sin grupo.",
        ["confirm.title"] = "Confirmar",

        ["weather.loading"] = "Cargando...",
        ["weather.gusts"] = "Ráf.",
        ["weather.next_days"] = "PRÓXIMOS DÍAS",
        ["weather.today"] = "HOY",
        ["weather.load_error"] = "No se pudo cargar el tiempo.\nComprueba tu conexión.",
        ["weather.clear"] = "Cielo despejado",
        ["weather.mainly_clear"] = "Mayormente despejado",
        ["weather.partly_cloudy"] = "Parcialmente nublado",
        ["weather.overcast"] = "Cubierto",
        ["weather.fog"] = "Niebla",
        ["weather.drizzle_light"] = "Llovizna ligera",
        ["weather.drizzle"] = "Llovizna",
        ["weather.drizzle_dense"] = "Llovizna densa",
        ["weather.drizzle_freezing"] = "Llovizna helada",
        ["weather.rain_light"] = "Lluvia ligera",
        ["weather.rain"] = "Lluvia",
        ["weather.rain_heavy"] = "Lluvia intensa",
        ["weather.rain_freezing"] = "Lluvia helada",
        ["weather.snow_light"] = "Nieve ligera",
        ["weather.snow"] = "Nieve",
        ["weather.snow_heavy"] = "Nieve intensa",
        ["weather.snow_grains"] = "Granos de nieve",
        ["weather.showers_light"] = "Chubascos ligeros",
        ["weather.showers"] = "Chubascos",
        ["weather.showers_violent"] = "Chubascos violentos",
        ["weather.snow_showers"] = "Chubascos de nieve",
        ["weather.snow_showers_heavy"] = "Fuertes chubascos de nieve",
        ["weather.thunderstorm"] = "Tormenta",
        ["weather.thunderstorm_hail"] = "Tormenta / granizo",
        ["weather.unknown"] = "Desconocido",

        ["hue.connect_network"] = "Conecta tu puente Philips Hue a la misma red que este PC.",
        ["hue.search_bridge"] = "Buscar puente",
        ["hue.searching"] = "Buscando puente...",
        ["hue.bridge_found"] = "Puente encontrado",
        ["hue.press_button_1"] = "Pulsa el ",
        ["hue.press_button_2"] = "botón físico",
        ["hue.press_button_3"] = " del puente,\nluego haz clic en Conectar.",
        ["hue.connect"] = "Conectar",
        ["hue.connecting"] = "Conectando...",
        ["hue.retry"] = "Reintentar",
        ["hue.reconfigure"] = "Reconfigurar puente",
        ["hue.home"] = "Casa",
        ["hue.rooms"] = "HABITACIONES",
        ["hue.scenes"] = "ESCENAS",
        ["hue.lights"] = "LUCES",
        ["hue.no_rooms"] = "No se encontraron habitaciones.\nComprueba la configuración de Hue.",
        ["hue.bridge_error"] = "Error de conexión al puente:\n{0}",
        ["hue.no_bridge"] = "No se encontró ningún puente Philips Hue en la red.\nAsegúrate de que esté encendido y conectado.",
        ["hue.pair_error"] = "Error de emparejamiento.",

        ["shutters.connecting"] = "Conectando a la caja…",
        ["shutters.reconnect"] = "Reconectar",
        ["shutters.title"] = "Persianas",
        ["shutters.all"] = "TODAS LAS PERSIANAS",
        ["shutters.up"] = "Subir",
        ["shutters.stop"] = "Parar",
        ["shutters.down"] = "Bajar",
        ["shutters.all_up"] = "Subir todas",
        ["shutters.all_stop"] = "Parar todas",
        ["shutters.all_down"] = "Bajar todas",
        ["shutters.ground_floor"] = "PLANTA BAJA",
        ["shutters.floor"] = "PISO SUPERIOR",
        ["shutters.close_floor"] = "Cerrar",
        ["shutters.close_gf_tip"] = "Cerrar planta baja",
        ["shutters.close_floor_tip"] = "Cerrar piso superior",
        ["shutters.sending"] = "Enviando…",
        ["shutters.connect_failed"] = "No se pudo conectar a {0}:{1}.\nComprueba la IP y las credenciales en Ajustes.",
        ["shutters.auth_failed"] = "Autenticación fallida (usuario: {0}).\n{1}",
        ["shutters.timeout"] = "Tiempo de espera agotado al conectar a {0}:{1}.\n¿Está la caja encendida y accesible?",
        ["shutters.network_error"] = "Error de red: {0}\n({1}:{2})",
        ["shutters.connect_error"] = "Error de conexión: {0}",
        ["shutters.login_no_response"] = "Sin respuesta tras el login (~{0} ms).",
        ["shutters.login_response"] = "Respuesta: \"{0}\" ({1})\nDuración de lectura: {2} ms",
        ["shutters.conn_closed"] = "Conexión cerrada.",
        ["shutters.hver_no_response"] = "HverRsp: sin respuesta o trama demasiado corta.",
        ["shutters.hver_unexpected"] = "Tras HverReq, recibido: {0} (se esperaba HverRsp).",
        ["shutters.dall_empty"] = "DallRsp recibido: deviceCount={0}. Ningún dispositivo filtrado como persiana.",
        ["shutters.frames_no_dall"] = "Tramas recibidas: {0}. Sin DallRsp.",
        ["shutters.no_frames"] = "Ninguna trama recibida tras GetaReq (timeout 15s).",
        ["shutters.timeout_frames"] = "Timeout. Tramas: {0}. Sin DallRsp.",
        ["shutters.timeout_geta"] = "Timeout de 15s tras GetaReq.",
        ["shutters.error"] = "Error: {0}",
        ["shutters.none_found"] = "Conectado, pero no se encontraron persianas en la caja.",
        ["shutters.none_found_diag"] = "Conectado, pero no se encontraron persianas en la caja.\n\nDiagnóstico: {0}",

        ["spotify.not_connected"] = "No conectado",
        ["spotify.connect"] = "Conectar a Spotify",
        ["spotify.no_playback"] = "Nada en reproducción",
        ["spotify.disconnect"] = "Desconectar",
        ["spotify.on_device"] = "En: {0}",
        ["spotify.connected"] = "Conectado",
        ["spotify.connected_ok"] = "Conectado a Spotify",
        ["spotify.not_configured"] = "Client ID / Secret de Spotify no configurados",
        ["spotify.disconnected"] = "Desconectado",
        ["spotify.opening_browser"] = "Abriendo el navegador...",
        ["spotify.browser_failed"] = "No se pudo abrir el navegador",
        ["spotify.wait_auth"] = "Esperando autorización en el navegador...",
        ["spotify.auth_cancelled"] = "Autorización cancelada",
        ["spotify.exchanging"] = "Intercambiando código...",
        ["spotify.auth_failed"] = "Autenticación fallida",
        ["spotify.auth_error"] = "Error de autorización",
        ["spotify.session_expired"] = "Sesión caducada",
        ["spotify.session_expired_reauth"] = "Sesión caducada, vuelve a conectarte",
        ["spotify.premium_required"] = "Se requiere Spotify Premium",
        ["spotify.premium_playback"] = "Se requiere Spotify Premium para controlar la reproducción",
        ["spotify.no_device_volume"] = "Ningún dispositivo Spotify activo para ajustar el volumen",
        ["spotify.playing"] = "Reproduciendo",
        ["spotify.paused"] = "En pausa",
        ["spotify.no_playback_status"] = "Nada en reproducción",
        ["spotify.fetch_error"] = "Error al obtener la reproducción",
        ["spotify.searching_device"] = "Buscando un dispositivo Spotify...",
        ["spotify.no_device"] = "Ningún dispositivo Spotify disponible. Abre Spotify en un dispositivo e inténtalo de nuevo.",
        ["spotify.transferring"] = "Transfiriendo a {0}...",
        ["spotify.transfer_failed"] = "No se pudo transferir la reproducción",
        ["spotify.api_error"] = "Error de la API de Spotify",
        ["spotify.no_track_like"] = "Ninguna pista de Spotify para añadir a Me gusta",
        ["spotify.like_auth"] = "Se requiere autorización de Spotify para Me gusta",
        ["spotify.like_scope"] = "Spotify no concedió permisos de Me gusta",
        ["spotify.like_unsupported"] = "Este contenido no se puede añadir a Me gusta",
        ["spotify.like_failed"] = "Error en Me gusta: {0}",
        ["spotify.like_error"] = "Error al actualizar Me gusta",
        ["spotify.oauth_fail_title"] = "Conexión fallida",
        ["spotify.oauth_ok_title"] = "Conectado",
        ["spotify.oauth_ok_body"] = "Puedes cerrar esta ventana y volver a PowerSideBar.",
        ["spotify.unknown_error"] = "Error desconocido",
    };

    private static readonly Dictionary<string, string> Ja = new()
    {
        ["common.cancel"] = "キャンセル",
        ["common.ok"] = "OK",
        ["common.add"] = "追加",
        ["common.save"] = "保存",
        ["common.loading"] = "読み込み中...",
        ["common.refresh"] = "更新",
        ["common.validation"] = "確認",
        ["common.close"] = "閉じる",
        ["common.delete"] = "削除",
        ["common.rename"] = "名前を変更",

        ["builtin.weather"] = "天気",
        ["builtin.hue"] = "Hue",
        ["builtin.shutters"] = "シャッター",

        ["app.already_running"] = "PowerSideBarは既に起動しています。",
        ["tray.show_hide"] = "表示/非表示",
        ["tray.auto_start"] = "Windows起動時に開始",
        ["tray.ad_block"] = "広告ブロッカー",
        ["tray.settings"] = "設定",
        ["tray.check_updates"] = "更新を確認",
        ["tray.quit"] = "終了",

        ["update.title"] = "更新",
        ["update.dev_only"] = "自動更新はインストール版（Setup）でのみ利用できます。",
        ["update.check_failed"] = "更新を確認できませんでした。\n{0}",
        ["update.up_to_date"] = "最新です（v{0}）。",
        ["update.available_title"] = "PowerSideBarの更新",
        ["update.available_body"] = "新しいバージョンがあります: v{0}\n現在のバージョン: v{1}\n\nダウンロードして今すぐ再起動しますか？",
        ["update.apply_failed"] = "ダウンロード / インストールに失敗しました。\n{0}",
        ["update.version_label"] = "インストール済みバージョン: v{0}",
        ["update.check_button"] = "更新を確認",

        ["settings.title"] = "設定",
        ["settings.nav.general"] = "一般",
        ["settings.nav.weather"] = "天気",
        ["settings.nav.hue"] = "Philips Hue",
        ["settings.nav.shutters"] = "シャッター",
        ["settings.nav.spotify"] = "Spotify",
        ["settings.general.title"] = "一般",
        ["settings.general.subtitle"] = "アプリの動作とサイドバーの外観。",
        ["settings.auto_start"] = "Windows起動時に自動で開始",
        ["settings.ad_block"] = "広告ブロッカー",
        ["settings.language"] = "言語",
        ["settings.lang.en"] = "英語",
        ["settings.lang.fr"] = "フランス語",
        ["settings.lang.es"] = "スペイン語",
        ["settings.lang.ja"] = "日本語",
        ["settings.language_restart"] = "新しい言語を適用するためにアプリを再起動します。",
        ["settings.bar_side"] = "サイドバーの位置",
        ["settings.side.left"] = "左",
        ["settings.side.right"] = "右",
        ["settings.bar_width"] = "サイドバーの幅",
        ["settings.width.narrow"] = "狭い",
        ["settings.width.normal"] = "標準",
        ["settings.width.wide"] = "広い",
        ["settings.updates"] = "更新",
        ["settings.support"] = "サポート",
        ["settings.kofi"] = "支援する",
        ["settings.weather.title"] = "天気",
        ["settings.weather.subtitle"] = "Open-Meteoで都市または郵便番号を検索し、結果を選択してください。",
        ["settings.weather.enable"] = "サイドバーに天気を表示",
        ["settings.weather.search"] = "都市または郵便番号を検索",
        ["settings.weather.city"] = "都市: {0}",
        ["settings.weather.no_city"] = "都市が選択されていません",
        ["settings.weather.no_results"] = "結果がありません。",
        ["settings.weather.search_error"] = "検索エラーです。もう一度お試しください。",
        ["settings.weather.need_city"] = "保存する前に検索結果から都市を選択してください。",
        ["settings.weather.min_chars"] = "2文字以上入力してください…",
        ["settings.weather.searching"] = "検索中…",
        ["settings.weather.results_count"] = "{0}件 — 都市を選択してください。",
        ["settings.hue.title"] = "Philips Hue",
        ["settings.hue.subtitle"] = "Hueブリッジを接続し、サイドバーからライトを操作します。",
        ["settings.hue.enable"] = "サイドバーにHueを表示",
        ["settings.hue.ip"] = "ブリッジIP",
        ["settings.hue.key"] = "APIキー",
        ["settings.shutters.title"] = "シャッター",
        ["settings.shutters.subtitle"] = "Dooya SHCボックスの接続設定。",
        ["settings.shutters.enable"] = "サイドバーにシャッターを表示",
        ["settings.shutters.host"] = "ホスト / IP",
        ["settings.shutters.port"] = "ポート",
        ["settings.shutters.user"] = "ユーザー名",
        ["settings.shutters.password"] = "パスワード",
        ["settings.shutters.host_id"] = "Host ID",
        ["settings.shutters.port_invalid"] = "シャッターのポートが無効です（1–65535）。",
        ["settings.spotify.title"] = "Spotify",
        ["settings.spotify.subtitle"] = "再生制御用のSpotify Developer認証情報。",
        ["settings.spotify.enable"] = "サイドバーにSpotifyを表示",
        ["settings.spotify.client_id"] = "Client ID",
        ["settings.spotify.client_secret"] = "Client Secret",

        ["sidebar.back"] = "戻る",
        ["sidebar.forward"] = "進む",
        ["sidebar.home"] = "ホーム",
        ["sidebar.refresh"] = "更新",
        ["sidebar.add_shortcut"] = "ショートカットを追加",
        ["sidebar.settings"] = "設定",
        ["sidebar.spotify"] = "Spotify",
        ["sidebar.like"] = "いいね",
        ["sidebar.previous"] = "前へ",
        ["sidebar.play_pause"] = "再生/一時停止",
        ["sidebar.next"] = "次へ",
        ["menu.rename_group"] = "グループ名を変更",
        ["menu.delete_group"] = "グループを削除",
        ["menu.rename"] = "名前を変更",
        ["menu.user_agent"] = "User Agent",
        ["menu.ua_mobile"] = "モバイル",
        ["menu.ua_desktop"] = "デスクトップ",
        ["menu.keep_background"] = "バックグラウンドで保持",
        ["menu.overlay"] = "オーバーレイモード",
        ["menu.close_on_collapse"] = "折りたたみ時に閉じる",
        ["menu.close_on_collapse_tip"] = "2回目のクリックでタブを閉じてメモリを解放します（そうしない場合はバックグラウンドに残ります）",
        ["menu.move_to_group"] = "移動...",
        ["menu.close_tab"] = "タブを閉じる",
        ["menu.delete"] = "削除",
        ["menu.no_group"] = "グループなし",
        ["menu.new_group"] = "新しいグループ...",
        ["dialog.new_group"] = "新しいグループ",
        ["dialog.rename"] = "名前を変更",
        ["dialog.rename_group"] = "グループ名を変更",
        ["dialog.add_shortcut"] = "ショートカットを追加",
        ["webview.runtime_missing"] = "WebView2 Runtimeが見つかりません。\n次からインストールしてください:\nhttps://developer.microsoft.com/en-us/microsoft-edge/webview2/\n\nエラー: {0}",
        ["webview.runtime_title"] = "PowerSideBar - エラー",
        ["dialog.name"] = "名前:",
        ["dialog.url"] = "URL:",
        ["dialog.browse_icon"] = "アイコンを選択...",
        ["dialog.name_required"] = "名前を入力してください。",
        ["dialog.url_required"] = "URLを入力してください。",
        ["confirm.delete_shortcut"] = "ショートカット「{0}」を削除しますか？",
        ["confirm.delete_group"] = "グループ「{0}」を削除しますか？ショートカットはグループ解除されます。",
        ["confirm.title"] = "確認",

        ["weather.loading"] = "読み込み中...",
        ["weather.gusts"] = "突風",
        ["weather.next_days"] = "今後の天気",
        ["weather.today"] = "今日",
        ["weather.load_error"] = "天気を読み込めませんでした。\n接続を確認してください。",
        ["weather.clear"] = "晴れ",
        ["weather.mainly_clear"] = "ほぼ晴れ",
        ["weather.partly_cloudy"] = "所により曇り",
        ["weather.overcast"] = "曇り",
        ["weather.fog"] = "霧",
        ["weather.drizzle_light"] = "弱い霧雨",
        ["weather.drizzle"] = "霧雨",
        ["weather.drizzle_dense"] = "強い霧雨",
        ["weather.drizzle_freezing"] = "着氷性の霧雨",
        ["weather.rain_light"] = "弱い雨",
        ["weather.rain"] = "雨",
        ["weather.rain_heavy"] = "強い雨",
        ["weather.rain_freezing"] = "着氷性の雨",
        ["weather.snow_light"] = "弱い雪",
        ["weather.snow"] = "雪",
        ["weather.snow_heavy"] = "強い雪",
        ["weather.snow_grains"] = "霧雪",
        ["weather.showers_light"] = "弱いにわか雨",
        ["weather.showers"] = "にわか雨",
        ["weather.showers_violent"] = "激しいにわか雨",
        ["weather.snow_showers"] = "にわか雪",
        ["weather.snow_showers_heavy"] = "激しいにわか雪",
        ["weather.thunderstorm"] = "雷雨",
        ["weather.thunderstorm_hail"] = "雷雨 / ひょう",
        ["weather.unknown"] = "不明",

        ["hue.connect_network"] = "Philips HueブリッジをこのPCと同じネットワークに接続してください。",
        ["hue.search_bridge"] = "ブリッジを検索",
        ["hue.searching"] = "ブリッジを検索中...",
        ["hue.bridge_found"] = "ブリッジが見つかりました",
        ["hue.press_button_1"] = "ブリッジの",
        ["hue.press_button_2"] = "物理ボタン",
        ["hue.press_button_3"] = "を押し、\n接続をクリックしてください。",
        ["hue.connect"] = "接続",
        ["hue.connecting"] = "接続中...",
        ["hue.retry"] = "再試行",
        ["hue.reconfigure"] = "ブリッジを再設定",
        ["hue.home"] = "ホーム",
        ["hue.rooms"] = "部屋",
        ["hue.scenes"] = "シーン",
        ["hue.lights"] = "ライト",
        ["hue.no_rooms"] = "部屋が見つかりません。\nHueの設定を確認してください。",
        ["hue.bridge_error"] = "ブリッジ接続エラー:\n{0}",
        ["hue.no_bridge"] = "ネットワーク上にPhilips Hueブリッジが見つかりません。\n電源が入っており接続されているか確認してください。",
        ["hue.pair_error"] = "ペアリングエラー。",

        ["shutters.connecting"] = "ボックスに接続中…",
        ["shutters.reconnect"] = "再接続",
        ["shutters.title"] = "シャッター",
        ["shutters.all"] = "すべてのシャッター",
        ["shutters.up"] = "上げる",
        ["shutters.stop"] = "停止",
        ["shutters.down"] = "下げる",
        ["shutters.all_up"] = "すべて上げる",
        ["shutters.all_stop"] = "すべて停止",
        ["shutters.all_down"] = "すべて下げる",
        ["shutters.ground_floor"] = "1階",
        ["shutters.floor"] = "上階",
        ["shutters.close_floor"] = "閉じる",
        ["shutters.close_gf_tip"] = "1階を閉じる",
        ["shutters.close_floor_tip"] = "上階を閉じる",
        ["shutters.sending"] = "送信中…",
        ["shutters.connect_failed"] = "{0}:{1} に接続できません。\n設定でIPと認証情報を確認してください。",
        ["shutters.auth_failed"] = "認証に失敗しました（ユーザー: {0}）。\n{1}",
        ["shutters.timeout"] = "{0}:{1} への接続がタイムアウトしました。\nボックスの電源と到達性を確認してください。",
        ["shutters.network_error"] = "ネットワークエラー: {0}\n({1}:{2})",
        ["shutters.connect_error"] = "接続エラー: {0}",
        ["shutters.login_no_response"] = "ログイン後に応答がありません（約 {0} ms）。",
        ["shutters.login_response"] = "応答: \"{0}\" ({1})\n読み取り時間: {2} ms",
        ["shutters.conn_closed"] = "接続が閉じられました。",
        ["shutters.hver_no_response"] = "HverRsp: 応答がないか、フレームが短すぎます。",
        ["shutters.hver_unexpected"] = "HverReqの後、受信: {0}（期待: HverRsp）。",
        ["shutters.dall_empty"] = "DallRsp受信: deviceCount={0}。シャッターとしてフィルタされたデバイスがありません。",
        ["shutters.frames_no_dall"] = "受信フレーム: {0}。DallRspなし。",
        ["shutters.no_frames"] = "GetaReqの後、フレームを受信しませんでした（15秒タイムアウト）。",
        ["shutters.timeout_frames"] = "タイムアウト。フレーム: {0}。DallRspなし。",
        ["shutters.timeout_geta"] = "GetaReqの後、15秒タイムアウト。",
        ["shutters.error"] = "エラー: {0}",
        ["shutters.none_found"] = "接続しましたが、ボックスにシャッターが見つかりません。",
        ["shutters.none_found_diag"] = "接続しましたが、ボックスにシャッターが見つかりません。\n\n診断: {0}",

        ["spotify.not_connected"] = "未接続",
        ["spotify.connect"] = "Spotifyに接続",
        ["spotify.no_playback"] = "再生中の曲なし",
        ["spotify.disconnect"] = "切断",
        ["spotify.on_device"] = "デバイス: {0}",
        ["spotify.connected"] = "接続済み",
        ["spotify.connected_ok"] = "Spotifyに接続しました",
        ["spotify.not_configured"] = "Spotify Client ID / Secretが設定されていません",
        ["spotify.disconnected"] = "切断されました",
        ["spotify.opening_browser"] = "ブラウザを開いています...",
        ["spotify.browser_failed"] = "ブラウザを開けませんでした",
        ["spotify.wait_auth"] = "ブラウザでの承認を待っています...",
        ["spotify.auth_cancelled"] = "承認がキャンセルされました",
        ["spotify.exchanging"] = "コードを交換中...",
        ["spotify.auth_failed"] = "認証に失敗しました",
        ["spotify.auth_error"] = "承認エラー",
        ["spotify.session_expired"] = "セッションの有効期限切れ",
        ["spotify.session_expired_reauth"] = "セッションの有効期限切れです。再接続してください",
        ["spotify.premium_required"] = "Spotify Premiumが必要です",
        ["spotify.premium_playback"] = "再生を制御するにはSpotify Premiumが必要です",
        ["spotify.no_device_volume"] = "音量を設定できるアクティブなSpotifyデバイスがありません",
        ["spotify.playing"] = "再生中",
        ["spotify.paused"] = "一時停止",
        ["spotify.no_playback_status"] = "再生中の曲なし",
        ["spotify.fetch_error"] = "再生情報の取得エラー",
        ["spotify.searching_device"] = "Spotifyデバイスを探しています...",
        ["spotify.no_device"] = "利用可能なSpotifyデバイスがありません。デバイスでSpotifyを開いてから再試行してください。",
        ["spotify.transferring"] = "{0} に転送中...",
        ["spotify.transfer_failed"] = "再生を転送できませんでした",
        ["spotify.api_error"] = "Spotify APIエラー",
        ["spotify.no_track_like"] = "お気に入りに追加するSpotifyトラックがありません",
        ["spotify.like_auth"] = "お気に入りにはSpotifyの承認が必要です",
        ["spotify.like_scope"] = "Spotifyがお気に入りの権限を付与しませんでした",
        ["spotify.like_unsupported"] = "このコンテンツはお気に入りに追加できません",
        ["spotify.like_failed"] = "お気に入りの更新に失敗: {0}",
        ["spotify.like_error"] = "お気に入りの更新エラー",
        ["spotify.oauth_fail_title"] = "接続に失敗しました",
        ["spotify.oauth_ok_title"] = "接続完了",
        ["spotify.oauth_ok_body"] = "このウィンドウを閉じてPowerSideBarに戻れます。",
        ["spotify.unknown_error"] = "不明なエラー",
    };
}

/// <summary>XAML markup: Text="{loc:Loc settings.title}"</summary>
[MarkupExtensionReturnType(typeof(string))]
public sealed class LocExtension : MarkupExtension
{
    public LocExtension() { }

    public LocExtension(string key) => Key = key;

    public string Key { get; set; } = string.Empty;

    public override object ProvideValue(IServiceProvider serviceProvider) =>
        string.IsNullOrEmpty(Key) ? string.Empty : Loc.T(Key);
}
