using System;
using System.Collections.Generic;
using System.Globalization;
using System.Windows;
using System.Windows.Markup;

namespace PowerSideBar.Services;

/// <summary>
/// Simple EN/FR localization. Default language is English.
/// Call <see cref="SetLanguage"/> before creating UI; restart the app after a language change.
/// </summary>
public static class Loc
{
    public const string English = "en";
    public const string French = "fr";

    private static string _language = English;
    private static IReadOnlyDictionary<string, string>? _strings;

    public static string Language => _language;

    public static CultureInfo Culture =>
        _language == French
            ? CultureInfo.GetCultureInfo("fr-FR")
            : CultureInfo.GetCultureInfo("en-US");

    public static void SetLanguage(string? language)
    {
        var lang = Normalize(language);
        _language = lang;
        _strings = lang == French ? Fr : En;
        try
        {
            CultureInfo.DefaultThreadCurrentCulture = Culture;
            CultureInfo.DefaultThreadCurrentUICulture = Culture;
        }
        catch
        {
            // Ignore culture failures in restricted environments.
        }
    }

    public static string Normalize(string? language) =>
        string.Equals(language, French, StringComparison.OrdinalIgnoreCase) ? French : English;

    public static string T(string key)
    {
        var map = _strings ?? En;
        return map.TryGetValue(key, out var value) ? value : key;
    }

    public static string Tf(string key, params object[] args) =>
        string.Format(Culture, T(key), args);

    private static readonly Dictionary<string, string> En = new()
    {
        // Common
        ["common.cancel"] = "Cancel",
        ["common.ok"] = "OK",
        ["common.add"] = "Add",
        ["common.save"] = "Save",
        ["common.loading"] = "Loading...",
        ["common.refresh"] = "Refresh",
        ["common.validation"] = "Validation",
        ["common.close"] = "Close",
        ["common.delete"] = "Delete",
        ["common.rename"] = "Rename",

        // Built-ins
        ["builtin.weather"] = "Weather",
        ["builtin.hue"] = "Hue",
        ["builtin.shutters"] = "Shutters",

        // Tray / App
        ["app.already_running"] = "PowerSideBar is already running.",
        ["tray.show_hide"] = "Show/Hide",
        ["tray.auto_start"] = "Start with Windows",
        ["tray.ad_block"] = "Ad blocker",
        ["tray.settings"] = "Settings",
        ["tray.check_updates"] = "Check for updates",
        ["tray.quit"] = "Quit",

        // Updates
        ["update.title"] = "Updates",
        ["update.dev_only"] = "Automatic updates are only available with the installed version (Setup).",
        ["update.check_failed"] = "Unable to check for updates.\n{0}",
        ["update.up_to_date"] = "You are up to date (v{0}).",
        ["update.available_title"] = "PowerSideBar update",
        ["update.available_body"] = "A new version is available: v{0}\nCurrent version: v{1}\n\nDownload and restart now?",
        ["update.apply_failed"] = "Download / install failed.\n{0}",
        ["update.version_label"] = "Installed version: v{0}",
        ["update.check_button"] = "Check for updates",

        // Settings
        ["settings.title"] = "Settings",
        ["settings.nav.general"] = "General",
        ["settings.nav.weather"] = "Weather",
        ["settings.nav.hue"] = "Philips Hue",
        ["settings.nav.shutters"] = "Shutters",
        ["settings.nav.spotify"] = "Spotify",
        ["settings.general.title"] = "General",
        ["settings.general.subtitle"] = "App behavior and sidebar appearance.",
        ["settings.auto_start"] = "Start automatically with Windows",
        ["settings.ad_block"] = "Ad blocker",
        ["settings.language"] = "Language",
        ["settings.lang.en"] = "English",
        ["settings.lang.fr"] = "French",
        ["settings.language_restart"] = "The app will restart to apply the new language.",
        ["settings.bar_side"] = "Sidebar position",
        ["settings.side.left"] = "Left",
        ["settings.side.right"] = "Right",
        ["settings.bar_width"] = "Sidebar width",
        ["settings.width.narrow"] = "Narrow",
        ["settings.width.normal"] = "Normal",
        ["settings.width.wide"] = "Wide",
        ["settings.updates"] = "Updates",
        ["settings.weather.title"] = "Weather",
        ["settings.weather.subtitle"] = "Search for a city or postal code via Open-Meteo, then select a result.",
        ["settings.weather.enable"] = "Show Weather in the sidebar",
        ["settings.weather.search"] = "Search for a city or postal code",
        ["settings.weather.city"] = "City: {0}",
        ["settings.weather.no_city"] = "No city selected",
        ["settings.weather.no_results"] = "No results.",
        ["settings.weather.search_error"] = "Search error. Please try again.",
        ["settings.weather.need_city"] = "Select a city from the search results before saving.",
        ["settings.weather.min_chars"] = "Enter at least 2 characters…",
        ["settings.weather.searching"] = "Searching…",
        ["settings.weather.results_count"] = "{0} result(s) — select a city.",
        ["settings.hue.title"] = "Philips Hue",
        ["settings.hue.subtitle"] = "Connect your Hue bridge and control lights from the sidebar.",
        ["settings.hue.enable"] = "Show Hue in the sidebar",
        ["settings.hue.ip"] = "Bridge IP",
        ["settings.hue.key"] = "API key",
        ["settings.shutters.title"] = "Shutters",
        ["settings.shutters.subtitle"] = "Dooya SHC box connection settings.",
        ["settings.shutters.enable"] = "Show Shutters in the sidebar",
        ["settings.shutters.host"] = "Host / IP",
        ["settings.shutters.port"] = "Port",
        ["settings.shutters.user"] = "Username",
        ["settings.shutters.password"] = "Password",
        ["settings.shutters.host_id"] = "Host ID",
        ["settings.shutters.port_invalid"] = "Invalid shutter port (1–65535).",
        ["settings.spotify.title"] = "Spotify",
        ["settings.spotify.subtitle"] = "Spotify Developer credentials for playback control.",
        ["settings.spotify.enable"] = "Show Spotify in the sidebar",
        ["settings.spotify.client_id"] = "Client ID",
        ["settings.spotify.client_secret"] = "Client Secret",

        // Sidebar chrome
        ["sidebar.back"] = "Back",
        ["sidebar.forward"] = "Forward",
        ["sidebar.home"] = "Home",
        ["sidebar.refresh"] = "Refresh",
        ["sidebar.add_shortcut"] = "Add shortcut",
        ["sidebar.settings"] = "Settings",
        ["sidebar.spotify"] = "Spotify",
        ["sidebar.like"] = "Like",
        ["sidebar.previous"] = "Previous",
        ["sidebar.play_pause"] = "Play/Pause",
        ["sidebar.next"] = "Next",
        ["menu.rename_group"] = "Rename group",
        ["menu.delete_group"] = "Delete group",
        ["menu.rename"] = "Rename",
        ["menu.user_agent"] = "User Agent",
        ["menu.ua_mobile"] = "Mobile",
        ["menu.ua_desktop"] = "Desktop",
        ["menu.keep_background"] = "Keep in background",
        ["menu.overlay"] = "Overlay mode",
        ["menu.close_on_collapse"] = "Close when collapsing",
        ["menu.close_on_collapse_tip"] = "On the second click, close the tab and free memory (otherwise it stays in the background)",
        ["menu.move_to_group"] = "Move to...",
        ["menu.close_tab"] = "Close tab",
        ["menu.delete"] = "Delete",
        ["menu.no_group"] = "No group",
        ["menu.new_group"] = "New group...",
        ["dialog.new_group"] = "New group",
        ["dialog.rename"] = "Rename",
        ["dialog.rename_group"] = "Rename group",
        ["dialog.add_shortcut"] = "Add shortcut",
        ["webview.runtime_missing"] = "WebView2 Runtime not found.\nInstall it from:\nhttps://developer.microsoft.com/en-us/microsoft-edge/webview2/\n\nError: {0}",
        ["webview.runtime_title"] = "PowerSideBar - Error",
        ["dialog.name"] = "Name:",
        ["dialog.url"] = "URL:",
        ["dialog.browse_icon"] = "Browse icon...",
        ["dialog.name_required"] = "Please enter a name.",
        ["dialog.url_required"] = "Please enter a URL.",
        ["confirm.delete_shortcut"] = "Delete shortcut \"{0}\"?",
        ["confirm.delete_group"] = "Delete group \"{0}\"? Shortcuts will be ungrouped.",
        ["confirm.title"] = "Confirm",

        // Weather panel
        ["weather.loading"] = "Loading...",
        ["weather.gusts"] = "Gusts",
        ["weather.next_days"] = "NEXT DAYS",
        ["weather.today"] = "TODAY",
        ["weather.load_error"] = "Unable to load weather.\nCheck your connection.",
        ["weather.clear"] = "Clear sky",
        ["weather.mainly_clear"] = "Mainly clear",
        ["weather.partly_cloudy"] = "Partly cloudy",
        ["weather.overcast"] = "Overcast",
        ["weather.fog"] = "Fog",
        ["weather.drizzle_light"] = "Light drizzle",
        ["weather.drizzle"] = "Drizzle",
        ["weather.drizzle_dense"] = "Dense drizzle",
        ["weather.drizzle_freezing"] = "Freezing drizzle",
        ["weather.rain_light"] = "Light rain",
        ["weather.rain"] = "Rain",
        ["weather.rain_heavy"] = "Heavy rain",
        ["weather.rain_freezing"] = "Freezing rain",
        ["weather.snow_light"] = "Light snow",
        ["weather.snow"] = "Snow",
        ["weather.snow_heavy"] = "Heavy snow",
        ["weather.snow_grains"] = "Snow grains",
        ["weather.showers_light"] = "Light showers",
        ["weather.showers"] = "Showers",
        ["weather.showers_violent"] = "Violent showers",
        ["weather.snow_showers"] = "Snow showers",
        ["weather.snow_showers_heavy"] = "Heavy snow showers",
        ["weather.thunderstorm"] = "Thunderstorm",
        ["weather.thunderstorm_hail"] = "Thunderstorm / hail",
        ["weather.unknown"] = "Unknown",

        // Hue
        ["hue.connect_network"] = "Connect your Philips Hue bridge to the same network as this PC.",
        ["hue.search_bridge"] = "Search for bridge",
        ["hue.searching"] = "Searching for bridge...",
        ["hue.bridge_found"] = "Bridge found",
        ["hue.press_button_1"] = "Press the ",
        ["hue.press_button_2"] = "physical button",
        ["hue.press_button_3"] = " on the bridge,\nthen click Connect.",
        ["hue.connect"] = "Connect",
        ["hue.connecting"] = "Connecting...",
        ["hue.retry"] = "Retry",
        ["hue.reconfigure"] = "Reconfigure bridge",
        ["hue.home"] = "Home",
        ["hue.rooms"] = "ROOMS",
        ["hue.scenes"] = "SCENES",
        ["hue.lights"] = "LIGHTS",
        ["hue.no_rooms"] = "No rooms found.\nCheck your Hue configuration.",
        ["hue.bridge_error"] = "Bridge connection error:\n{0}",
        ["hue.no_bridge"] = "No Philips Hue bridge found on the network.\nMake sure it is powered on and connected.",
        ["hue.pair_error"] = "Pairing error.",

        // Shutters
        ["shutters.connecting"] = "Connecting to the box…",
        ["shutters.reconnect"] = "Reconnect",
        ["shutters.title"] = "Shutters",
        ["shutters.all"] = "ALL SHUTTERS",
        ["shutters.up"] = "Up",
        ["shutters.stop"] = "Stop",
        ["shutters.down"] = "Down",
        ["shutters.all_up"] = "Raise all",
        ["shutters.all_stop"] = "Stop all",
        ["shutters.all_down"] = "Lower all",
        ["shutters.ground_floor"] = "GROUND FLOOR",
        ["shutters.floor"] = "UPPER FLOOR",
        ["shutters.close_floor"] = "Close",
        ["shutters.close_gf_tip"] = "Close ground floor",
        ["shutters.close_floor_tip"] = "Close upper floor",
        ["shutters.sending"] = "Sending…",
        ["shutters.connect_failed"] = "Unable to connect to {0}:{1}.\nCheck the IP and credentials in Settings.",
        ["shutters.auth_failed"] = "Authentication failed (user: {0}).\n{1}",
        ["shutters.timeout"] = "Timed out connecting to {0}:{1}.\nIs the box powered on and reachable?",
        ["shutters.network_error"] = "Network error: {0}\n({1}:{2})",
        ["shutters.connect_error"] = "Connection error: {0}",
        ["shutters.login_no_response"] = "No response after login (~{0} ms).",
        ["shutters.login_response"] = "Response: \"{0}\" ({1})\nRead duration: {2} ms",
        ["shutters.conn_closed"] = "Connection closed.",
        ["shutters.hver_no_response"] = "HverRsp: no response or frame too short.",
        ["shutters.hver_unexpected"] = "After HverReq, received: {0} (expected HverRsp).",
        ["shutters.dall_empty"] = "DallRsp received: deviceCount={0}. No device filtered as a shutter.",
        ["shutters.frames_no_dall"] = "Frames received: {0}. No DallRsp.",
        ["shutters.no_frames"] = "No frames received after GetaReq (15s timeout).",
        ["shutters.timeout_frames"] = "Timeout. Frames: {0}. No DallRsp.",
        ["shutters.timeout_geta"] = "15s timeout after GetaReq.",
        ["shutters.error"] = "Error: {0}",
        ["shutters.none_found"] = "Connected, but no shutters found on the box.",
        ["shutters.none_found_diag"] = "Connected, but no shutters found on the box.\n\nDiagnostic: {0}",

        // Spotify
        ["spotify.not_connected"] = "Not connected",
        ["spotify.connect"] = "Connect to Spotify",
        ["spotify.no_playback"] = "Nothing playing",
        ["spotify.disconnect"] = "Disconnect",
        ["spotify.on_device"] = "On: {0}",
        ["spotify.connected"] = "Connected",
        ["spotify.connected_ok"] = "Connected to Spotify",
        ["spotify.not_configured"] = "Spotify Client ID / Secret not configured",
        ["spotify.disconnected"] = "Disconnected",
        ["spotify.opening_browser"] = "Opening browser...",
        ["spotify.browser_failed"] = "Unable to open the browser",
        ["spotify.wait_auth"] = "Waiting for authorization in the browser...",
        ["spotify.auth_cancelled"] = "Authorization cancelled",
        ["spotify.exchanging"] = "Exchanging code...",
        ["spotify.auth_failed"] = "Authentication failed",
        ["spotify.auth_error"] = "Authorization error",
        ["spotify.session_expired"] = "Session expired",
        ["spotify.session_expired_reauth"] = "Session expired, please reconnect",
        ["spotify.premium_required"] = "Spotify Premium required",
        ["spotify.premium_playback"] = "Spotify Premium required to control playback",
        ["spotify.no_device_volume"] = "No active Spotify device to set volume",
        ["spotify.playing"] = "Playing",
        ["spotify.paused"] = "Paused",
        ["spotify.no_playback_status"] = "Nothing playing",
        ["spotify.fetch_error"] = "Error while fetching playback",
        ["spotify.searching_device"] = "Looking for a Spotify device...",
        ["spotify.no_device"] = "No Spotify device available. Open Spotify on a device, then try again.",
        ["spotify.transferring"] = "Transferring to {0}...",
        ["spotify.transfer_failed"] = "Unable to transfer playback",
        ["spotify.api_error"] = "Spotify API error",
        ["spotify.no_track_like"] = "No Spotify track to add to Liked Songs",
        ["spotify.like_auth"] = "Spotify authorization required for Liked Songs",
        ["spotify.like_scope"] = "Spotify did not grant Liked Songs permissions",
        ["spotify.like_unsupported"] = "This content cannot be added to Liked Songs",
        ["spotify.like_failed"] = "Liked Songs failed: {0}",
        ["spotify.like_error"] = "Error updating Liked Songs",
        ["spotify.oauth_fail_title"] = "Connection failed",
        ["spotify.oauth_ok_title"] = "Connected",
        ["spotify.oauth_ok_body"] = "You can close this window and return to PowerSideBar.",
        ["spotify.unknown_error"] = "Unknown error",
    };

    private static readonly Dictionary<string, string> Fr = new()
    {
        ["common.cancel"] = "Annuler",
        ["common.ok"] = "OK",
        ["common.add"] = "Ajouter",
        ["common.save"] = "Enregistrer",
        ["common.loading"] = "Chargement...",
        ["common.refresh"] = "Actualiser",
        ["common.validation"] = "Validation",
        ["common.close"] = "Fermer",
        ["common.delete"] = "Supprimer",
        ["common.rename"] = "Renommer",

        ["builtin.weather"] = "Météo",
        ["builtin.hue"] = "Hue",
        ["builtin.shutters"] = "Volets",

        ["app.already_running"] = "PowerSideBar est déjà en cours d'exécution.",
        ["tray.show_hide"] = "Afficher/Masquer",
        ["tray.auto_start"] = "Démarrage auto",
        ["tray.ad_block"] = "Bloqueur de pub",
        ["tray.settings"] = "Paramètres",
        ["tray.check_updates"] = "Vérifier les mises à jour",
        ["tray.quit"] = "Quitter",

        ["update.title"] = "Mises à jour",
        ["update.dev_only"] = "Les mises à jour automatiques sont disponibles uniquement avec la version installée (Setup).",
        ["update.check_failed"] = "Impossible de vérifier les mises à jour.\n{0}",
        ["update.up_to_date"] = "Vous êtes à jour (v{0}).",
        ["update.available_title"] = "Mise à jour PowerSideBar",
        ["update.available_body"] = "Une nouvelle version est disponible : v{0}\nVersion actuelle : v{1}\n\nTélécharger et redémarrer maintenant ?",
        ["update.apply_failed"] = "Échec du téléchargement / de l'installation.\n{0}",
        ["update.version_label"] = "Version installée : v{0}",
        ["update.check_button"] = "Vérifier les mises à jour",

        ["settings.title"] = "Paramètres",
        ["settings.nav.general"] = "Général",
        ["settings.nav.weather"] = "Météo",
        ["settings.nav.hue"] = "Philips Hue",
        ["settings.nav.shutters"] = "Volets",
        ["settings.nav.spotify"] = "Spotify",
        ["settings.general.title"] = "Général",
        ["settings.general.subtitle"] = "Comportement de l'application et apparence de la barre.",
        ["settings.auto_start"] = "Démarrage automatique avec Windows",
        ["settings.ad_block"] = "Bloqueur de publicités",
        ["settings.language"] = "Langue",
        ["settings.lang.en"] = "Anglais",
        ["settings.lang.fr"] = "Français",
        ["settings.language_restart"] = "L'application va redémarrer pour appliquer la nouvelle langue.",
        ["settings.bar_side"] = "Position de la barre",
        ["settings.side.left"] = "Gauche",
        ["settings.side.right"] = "Droite",
        ["settings.bar_width"] = "Largeur de la barre",
        ["settings.width.narrow"] = "Étroit",
        ["settings.width.normal"] = "Normal",
        ["settings.width.wide"] = "Large",
        ["settings.updates"] = "Mises à jour",
        ["settings.weather.title"] = "Météo",
        ["settings.weather.subtitle"] = "Recherchez une ville ou un code postal via Open-Meteo, puis sélectionnez un résultat.",
        ["settings.weather.enable"] = "Afficher Météo dans la barre",
        ["settings.weather.search"] = "Rechercher une ville ou un code postal",
        ["settings.weather.city"] = "Ville : {0}",
        ["settings.weather.no_city"] = "Aucune ville sélectionnée",
        ["settings.weather.no_results"] = "Aucun résultat.",
        ["settings.weather.search_error"] = "Erreur de recherche. Réessayez.",
        ["settings.weather.need_city"] = "Sélectionnez une ville dans les résultats avant d'enregistrer.",
        ["settings.weather.min_chars"] = "Saisissez au moins 2 caractères…",
        ["settings.weather.searching"] = "Recherche…",
        ["settings.weather.results_count"] = "{0} résultat(s) — sélectionnez une ville.",
        ["settings.hue.title"] = "Philips Hue",
        ["settings.hue.subtitle"] = "Connectez votre bridge Hue et contrôlez les lumières depuis la barre.",
        ["settings.hue.enable"] = "Afficher Hue dans la barre",
        ["settings.hue.ip"] = "IP du bridge",
        ["settings.hue.key"] = "Clé API",
        ["settings.shutters.title"] = "Volets",
        ["settings.shutters.subtitle"] = "Paramètres de connexion au boîtier Dooya SHC.",
        ["settings.shutters.enable"] = "Afficher Volets dans la barre",
        ["settings.shutters.host"] = "Hôte / IP",
        ["settings.shutters.port"] = "Port",
        ["settings.shutters.user"] = "Utilisateur",
        ["settings.shutters.password"] = "Mot de passe",
        ["settings.shutters.host_id"] = "Host ID",
        ["settings.shutters.port_invalid"] = "Port volets invalide (1–65535).",
        ["settings.spotify.title"] = "Spotify",
        ["settings.spotify.subtitle"] = "Identifiants Spotify Developer pour le contrôle de la lecture.",
        ["settings.spotify.enable"] = "Afficher Spotify dans la barre",
        ["settings.spotify.client_id"] = "Client ID",
        ["settings.spotify.client_secret"] = "Client Secret",

        ["sidebar.back"] = "Retour",
        ["sidebar.forward"] = "Avancer",
        ["sidebar.home"] = "Accueil",
        ["sidebar.refresh"] = "Rafraîchir",
        ["sidebar.add_shortcut"] = "Ajouter un raccourci",
        ["sidebar.settings"] = "Paramètres",
        ["sidebar.spotify"] = "Spotify",
        ["sidebar.like"] = "J'aime",
        ["sidebar.previous"] = "Précédent",
        ["sidebar.play_pause"] = "Play/Pause",
        ["sidebar.next"] = "Suivant",
        ["menu.rename_group"] = "Renommer le groupe",
        ["menu.delete_group"] = "Supprimer le groupe",
        ["menu.rename"] = "Renommer",
        ["menu.user_agent"] = "User Agent",
        ["menu.ua_mobile"] = "Mobile",
        ["menu.ua_desktop"] = "Desktop",
        ["menu.keep_background"] = "Garder en arrière-plan",
        ["menu.overlay"] = "Passer par-dessus",
        ["menu.close_on_collapse"] = "Fermer en réduisant",
        ["menu.close_on_collapse_tip"] = "Au second clic, ferme l'onglet et libère la mémoire (sinon il reste en arrière-plan)",
        ["menu.move_to_group"] = "Déplacer vers...",
        ["menu.close_tab"] = "Fermer l'onglet",
        ["menu.delete"] = "Supprimer",
        ["menu.no_group"] = "Aucun groupe",
        ["menu.new_group"] = "Nouveau groupe...",
        ["dialog.new_group"] = "Nouveau groupe",
        ["dialog.rename"] = "Renommer",
        ["dialog.rename_group"] = "Renommer le groupe",
        ["dialog.add_shortcut"] = "Ajouter un raccourci",
        ["webview.runtime_missing"] = "WebView2 Runtime introuvable.\nInstallez-le depuis :\nhttps://developer.microsoft.com/en-us/microsoft-edge/webview2/\n\nErreur : {0}",
        ["webview.runtime_title"] = "PowerSideBar - Erreur",
        ["dialog.name"] = "Nom :",
        ["dialog.url"] = "URL :",
        ["dialog.browse_icon"] = "Parcourir icône...",
        ["dialog.name_required"] = "Veuillez entrer un nom.",
        ["dialog.url_required"] = "Veuillez entrer une URL.",
        ["confirm.delete_shortcut"] = "Supprimer le raccourci « {0} » ?",
        ["confirm.delete_group"] = "Supprimer le groupe « {0} » ? Les raccourcis seront détachés.",
        ["confirm.title"] = "Confirmation",

        ["weather.loading"] = "Chargement...",
        ["weather.gusts"] = "Raf.",
        ["weather.next_days"] = "PROCHAINS JOURS",
        ["weather.today"] = "AUJOURD'HUI",
        ["weather.load_error"] = "Impossible de charger la météo.\nVérifiez votre connexion.",
        ["weather.clear"] = "Ciel clair",
        ["weather.mainly_clear"] = "Mitigé",
        ["weather.partly_cloudy"] = "Peu nuageux",
        ["weather.overcast"] = "Couvert",
        ["weather.fog"] = "Brouillard",
        ["weather.drizzle_light"] = "Bruine légère",
        ["weather.drizzle"] = "Bruine",
        ["weather.drizzle_dense"] = "Bruine dense",
        ["weather.drizzle_freezing"] = "Bruine verglaçante",
        ["weather.rain_light"] = "Pluie légère",
        ["weather.rain"] = "Pluie",
        ["weather.rain_heavy"] = "Pluie forte",
        ["weather.rain_freezing"] = "Pluie verglaçante",
        ["weather.snow_light"] = "Neige légère",
        ["weather.snow"] = "Neige",
        ["weather.snow_heavy"] = "Neige forte",
        ["weather.snow_grains"] = "Grains de neige",
        ["weather.showers_light"] = "Averses légères",
        ["weather.showers"] = "Averses",
        ["weather.showers_violent"] = "Averses violentes",
        ["weather.snow_showers"] = "Averses de neige",
        ["weather.snow_showers_heavy"] = "Fortes averses de neige",
        ["weather.thunderstorm"] = "Orage",
        ["weather.thunderstorm_hail"] = "Orage / grêle",
        ["weather.unknown"] = "Inconnu",

        ["hue.connect_network"] = "Connectez votre bridge Philips Hue au même réseau que ce PC.",
        ["hue.search_bridge"] = "Rechercher le bridge",
        ["hue.searching"] = "Recherche du bridge en cours...",
        ["hue.bridge_found"] = "Bridge trouvé",
        ["hue.press_button_1"] = "Appuyez sur le ",
        ["hue.press_button_2"] = "bouton physique",
        ["hue.press_button_3"] = " du bridge,\npuis cliquez sur Connecter.",
        ["hue.connect"] = "Connecter",
        ["hue.connecting"] = "Connexion en cours...",
        ["hue.retry"] = "Réessayer",
        ["hue.reconfigure"] = "Reconfigurer le bridge",
        ["hue.home"] = "Maison",
        ["hue.rooms"] = "PIÈCES",
        ["hue.scenes"] = "SCÈNES",
        ["hue.lights"] = "LUMIÈRES",
        ["hue.no_rooms"] = "Aucune pièce trouvée.\nVérifiez la configuration Hue.",
        ["hue.bridge_error"] = "Erreur de connexion au bridge :\n{0}",
        ["hue.no_bridge"] = "Aucun bridge Philips Hue trouvé sur le réseau.\nVérifiez qu'il est allumé et connecté.",
        ["hue.pair_error"] = "Erreur de couplage.",

        ["shutters.connecting"] = "Connexion au boîtier…",
        ["shutters.reconnect"] = "Reconnecter",
        ["shutters.title"] = "Volets",
        ["shutters.all"] = "TOUS LES VOLETS",
        ["shutters.up"] = "Monter",
        ["shutters.stop"] = "Stop",
        ["shutters.down"] = "Descendre",
        ["shutters.all_up"] = "Tout monter",
        ["shutters.all_stop"] = "Tout arrêter",
        ["shutters.all_down"] = "Tout descendre",
        ["shutters.ground_floor"] = "REZ-DE-CHAUSSÉE",
        ["shutters.floor"] = "ÉTAGE",
        ["shutters.close_floor"] = "Fermer",
        ["shutters.close_gf_tip"] = "Fermer le RDC",
        ["shutters.close_floor_tip"] = "Fermer l'étage",
        ["shutters.sending"] = "Envoi…",
        ["shutters.connect_failed"] = "Impossible de se connecter à {0}:{1}.\nVérifiez l'IP et les identifiants dans les paramètres.",
        ["shutters.auth_failed"] = "Échec auth (user: {0}).\n{1}",
        ["shutters.timeout"] = "Délai d'attente dépassé pour {0}:{1}.\nLe boîtier est-il allumé et accessible ?",
        ["shutters.network_error"] = "Erreur réseau : {0}\n({1}:{2})",
        ["shutters.connect_error"] = "Erreur de connexion : {0}",
        ["shutters.login_no_response"] = "Aucune réponse après login (~{0} ms).",
        ["shutters.login_response"] = "Réponse: \"{0}\" ({1})\nDurée lecture: {2} ms",
        ["shutters.conn_closed"] = "Connexion fermée.",
        ["shutters.hver_no_response"] = "HverRsp: aucune réponse ou trame trop courte.",
        ["shutters.hver_unexpected"] = "Après HverReq, reçu: {0} (attendu HverRsp).",
        ["shutters.dall_empty"] = "DallRsp reçu: deviceCount={0}. Aucun device filtré comme volet.",
        ["shutters.frames_no_dall"] = "Trames reçues: {0}. Pas de DallRsp.",
        ["shutters.no_frames"] = "Aucune trame reçue après GetaReq (timeout 15s).",
        ["shutters.timeout_frames"] = "Timeout. Trames: {0}. Pas de DallRsp.",
        ["shutters.timeout_geta"] = "Timeout 15s après GetaReq.",
        ["shutters.error"] = "Erreur: {0}",
        ["shutters.none_found"] = "Connecté, mais aucun volet trouvé sur le boîtier.",
        ["shutters.none_found_diag"] = "Connecté, mais aucun volet trouvé sur le boîtier.\n\nDiagnostic: {0}",

        ["spotify.not_connected"] = "Non connecté",
        ["spotify.connect"] = "Se connecter à Spotify",
        ["spotify.no_playback"] = "Aucune lecture",
        ["spotify.disconnect"] = "Se déconnecter",
        ["spotify.on_device"] = "Sur : {0}",
        ["spotify.connected"] = "Connecté",
        ["spotify.connected_ok"] = "Connecté à Spotify",
        ["spotify.not_configured"] = "Client ID / Secret Spotify non configurés",
        ["spotify.disconnected"] = "Déconnecté",
        ["spotify.opening_browser"] = "Ouverture du navigateur...",
        ["spotify.browser_failed"] = "Impossible d'ouvrir le navigateur",
        ["spotify.wait_auth"] = "En attente de l'autorisation dans le navigateur...",
        ["spotify.auth_cancelled"] = "Autorisation annulée",
        ["spotify.exchanging"] = "Échange du code...",
        ["spotify.auth_failed"] = "Échec de l'authentification",
        ["spotify.auth_error"] = "Erreur lors de l'autorisation",
        ["spotify.session_expired"] = "Session expirée",
        ["spotify.session_expired_reauth"] = "Session expirée, reconnectez-vous",
        ["spotify.premium_required"] = "Spotify Premium requis",
        ["spotify.premium_playback"] = "Spotify Premium requis pour contrôler la lecture",
        ["spotify.no_device_volume"] = "Aucun appareil Spotify actif pour régler le volume",
        ["spotify.playing"] = "En lecture",
        ["spotify.paused"] = "En pause",
        ["spotify.no_playback_status"] = "Aucune lecture en cours",
        ["spotify.fetch_error"] = "Erreur lors de la récupération",
        ["spotify.searching_device"] = "Recherche d'un appareil Spotify...",
        ["spotify.no_device"] = "Aucun appareil Spotify disponible. Ouvrez Spotify sur un appareil puis réessayez.",
        ["spotify.transferring"] = "Transfert vers {0}...",
        ["spotify.transfer_failed"] = "Impossible de transférer la lecture",
        ["spotify.api_error"] = "Erreur de l'API Spotify",
        ["spotify.no_track_like"] = "Aucun morceau Spotify à ajouter en favoris",
        ["spotify.like_auth"] = "Autorisation Spotify requise pour les favoris",
        ["spotify.like_scope"] = "Spotify n'a pas accordé les permissions Favoris",
        ["spotify.like_unsupported"] = "Ce contenu ne peut pas être ajouté aux favoris",
        ["spotify.like_failed"] = "Favoris KO: {0}",
        ["spotify.like_error"] = "Erreur lors de la mise à jour des favoris",
        ["spotify.oauth_fail_title"] = "Échec de la connexion",
        ["spotify.oauth_ok_title"] = "Connexion réussie",
        ["spotify.oauth_ok_body"] = "Vous pouvez fermer cette fenêtre et revenir à PowerSideBar.",
        ["spotify.unknown_error"] = "Erreur inconnue",
    };
}

/// <summary>XAML markup: Text="{loc:Loc settings.title}"</summary>
[MarkupExtensionReturnType(typeof(string))]
public sealed class LocExtension : MarkupExtension
{
    public LocExtension() { }

    public LocExtension(string key) => Key = key;

    public string Key { get; set; } = string.Empty;

    public override object ProvideValue(IServiceProvider serviceProvider) =>
        string.IsNullOrEmpty(Key) ? string.Empty : Loc.T(Key);
}
